version: '3'
services:
  web:
    # image: nginx:latest
    ports:
      - "4000:4000"
      # - "4000:80"
    volumes:
      - .:/app
      # - ./src:/usr/share/nginx/html
    build: .
    env_file:
      - .env
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - sharpbitdev:/var/lib/mysql
volumes:
  sharpbitdev:

